### ISSUE TITLE
nwabap version failed.

### ISSUE THREAD

**Issue by ksaito1125** [nrdev88/nwabap-ui5uploader#19]
When I execute the version command of the nwabap command, the following error appears.

```
internal/fs/utils.js:308
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/nwabap-ui5uploader/node_modules/figlet/fonts/isometric3.flf'
    at Object.openSync (fs.js:476:3)
    at Object.readFileSync (fs.js:377:35)
    at Function.figlet.loadFontSync (/usr/local/lib/node_modules/nwabap-ui5uploader/node_modules/figlet/lib/node-figlet.js:48:23)
    at Function.me.textSync (/usr/local/lib/node_modules/nwabap-ui5uploader/node_modules/figlet/lib/figlet.js:879:43)
    at Command.<anonymous> (/usr/local/lib/node_modules/nwabap-ui5uploader/cli/commands/version.js:16:28)
    at Command.listener (/usr/local/lib/node_modules/nwabap-ui5uploader/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:315:20)
    at Command.parseArgs (/usr/local/lib/node_modules/nwabap-ui5uploader/node_modules/commander/index.js:651:12)
    at Command.parse (/usr/local/lib/node_modules/nwabap-ui5uploader/node_modules/commander/index.js:474:21)
    at bootstrap (/usr/local/lib/node_modules/nwabap-ui5uploader/cli/bootstrap.js:13:13) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/usr/local/lib/node_modules/nwabap-ui5uploader/node_modules/figlet/fonts/isometric3.flf'
}
```

**Comment by ksaito1125** [comment]
```
$ docker run -it --rm node bash
root@093eaeccecc7:/# npm install -g nwabap-ui5uploader
...
root@093eaeccecc7:/# curl -s -o /usr/local/lib/node_modules/nwabap-ui5uploader/node_modules/figlet/fonts/isometric3.flf http://www.figlet.org/fonts/isometric3.flf
root@093eaeccecc7:/# nwabap version
      ___           ___           ___                         ___           ___   
     /__/\         /__/\         /  /\         _____         /  /\         /  /\  
     \  \:\       _\_ \:\       /  /::\       /  /::\       /  /::\       /  /::\ 
      \  \:\     /__/\ \:\     /  /:/\:\     /  /:/\:\     /  /:/\:\     /  /:/\:\
  _____\__\:\   _\_ \:\ \:\   /  /:/~/::\   /  /:/~/::\   /  /:/~/::\   /  /:/~/:/
 /__/::::::::\ /__/\ \:\ \:\ /__/:/ /:/\:\ /__/:/ /:/\:| /__/:/ /:/\:\ /__/:/ /:/ 
 \  \:\~~\~~\/ \  \:\ \:\/:/ \  \:\/:/__\/ \  \:\/:/~/:/ \  \:\/:/__\/ \  \:\/:/  
  \  \:\  ~~~   \  \:\ \::/   \  \::/       \  \::/ /:/   \  \::/       \  \::/   
   \  \:\        \  \:\/:/     \  \:\        \  \:\/:/     \  \:\        \  \:\   
    \  \:\        \  \::/       \  \:\        \  \::/       \  \:\        \  \:\  
     \__\/         \__\/         \__\/         \__\/         \__\/         \__\/   1.1.0
root@093eaeccecc7:/# 
```

**Comment by nrdev88** [comment]
I can't reproduce this. Are you behind a proxy?
